<?php

namespace Database\Seeders;

use App\Models\ServiceRequest;
use App\Models\User;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ServiceRequestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = User::all();
        $categories = Category::all();

        if ($users->isEmpty()) {
            $this->command->error('Please run UserSeeder first');
            return;
        }

        if ($categories->isEmpty()) {
            $this->command->error('Please run CategorySeeder first');
            return;
        }

        $serviceRequests = [
            [
                'title' => 'Urgent Plumbing Repair Needed',
                'description' => 'Water leak under kitchen sink needs immediate attention. The leak appears to be coming from the pipe connection and is causing water damage to the cabinet.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Plumbing', 'Emergency Services'],
            ],
            [
                'title' => 'Weekly House Cleaning Service',
                'description' => 'Looking for a professional cleaner for weekly house cleaning. 3 bedroom, 2 bathroom house. Tasks include dusting, vacuuming, mopping, and bathroom cleaning.',
                'priority' => 'medium',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Cleaning', 'Home Maintenance'],
            ],
            [
                'title' => 'Garden Landscaping Project',
                'description' => 'Need help redesigning and landscaping backyard garden. Area is approximately 500 sq ft. Looking for someone to create a modern, low-maintenance design.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'paypal',
                'categories' => ['Gardening', 'Home Maintenance'],
            ],
            [
                'title' => 'Private Math Tutoring for High School Student',
                'description' => 'Seeking an experienced math tutor for advanced calculus. Two sessions per week, 1.5 hours each. Must have teaching experience.',
                'priority' => 'medium',
                'visibility' => 'private',
                'service_type' => 'recurring',
                'payment_method' => 'credit_card',
                'categories' => ['Education', 'Tutoring'],
            ],
            [
                'title' => 'Emergency Electrical Repair',
                'description' => 'Power outage in half of the house. Circuit breaker issues. Need licensed electrician for immediate inspection and repair.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Electrical', 'Emergency Services'],
            ],
            [
                'title' => 'Monthly Pool Maintenance Service',
                'description' => 'Looking for regular pool maintenance including chemical balance, cleaning, and equipment check. Pool size is 15x30 feet.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Pool Service', 'Home Services'],
            ],
            [
                'title' => 'Professional Moving Assistance',
                'description' => 'Need help moving from a 2-bedroom apartment to a new house. Includes furniture disassembly/assembly. Distance is approximately 15 miles.',
                'priority' => 'medium',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'paypal',
                'categories' => ['Moving', 'Heavy Lifting'],
            ],
            [
                'title' => 'Private Chef for Special Dinner',
                'description' => 'Looking for a private chef to prepare a gourmet dinner for 8 people. Mediterranean cuisine preferred. Event is next month.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Cooking', 'Events'],
            ],
            [
                'title' => 'Computer Network Setup for Small Office',
                'description' => 'Need IT professional to set up network for small office. Includes router configuration, printer setup, and basic security measures.',
                'priority' => 'high',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'bank_transfer',
                'categories' => ['IT Services', 'Business Services'],
            ],
            [
                'title' => 'Home Security System Installation',
                'description' => 'Need professional installation of a complete home security system including cameras, motion sensors, and alarm system.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Security', 'Home Services'],
            ],
            [
                'title' => 'Regular Dog Walking Service',
                'description' => 'Looking for a reliable dog walker for daily walks. Medium-sized dog, needs 30-minute walks twice a day.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Pet Care', 'Dog Walking'],
            ],
            [
                'title' => 'Professional Photography for Wedding',
                'description' => 'Need a professional photographer for wedding ceremony and reception. Full day coverage required.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Photography', 'Events'],
            ],
            [
                'title' => 'HVAC System Maintenance',
                'description' => 'Regular maintenance check for central air conditioning and heating system. Includes filter replacement and system inspection.',
                'priority' => 'medium',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['HVAC', 'Home Services'],
            ],
            [
                'title' => 'Personal Fitness Training',
                'description' => 'Looking for a certified personal trainer for one-on-one sessions. Three times per week, focusing on strength training.',
                'priority' => 'medium',
                'visibility' => 'private',
                'service_type' => 'recurring',
                'payment_method' => 'credit_card',
                'categories' => ['Fitness', 'Personal Training'],
            ],
            [
                'title' => 'Website Development for Small Business',
                'description' => 'Need a professional website developer to create an e-commerce website for a small retail business.',
                'priority' => 'high',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'bank_transfer',
                'categories' => ['Web Development', 'Business Services'],
            ],
            [
                'title' => 'Emergency Roof Repair',
                'description' => 'Roof damage after recent storm. Need immediate repair to prevent water damage. Area affected is approximately 200 sq ft.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Roofing', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Lawn Care Service',
                'description' => 'Looking for weekly lawn maintenance including mowing, edging, and basic landscaping. Property is 1/4 acre.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Lawn Care', 'Landscaping'],
            ],
            [
                'title' => 'Professional Carpet Cleaning',
                'description' => 'Need deep cleaning for all carpets in a 3-bedroom house. Includes stain removal and deodorizing.',
                'priority' => 'medium',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Cleaning', 'Home Services'],
            ],
            [
                'title' => 'Private Music Lessons',
                'description' => 'Seeking a piano teacher for beginner lessons. One hour sessions, twice a week. Must have teaching experience.',
                'priority' => 'low',
                'visibility' => 'private',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Music', 'Education'],
            ],
            [
                'title' => 'Emergency Locksmith Service',
                'description' => 'Locked out of house. Need immediate assistance to regain access. Front door lock needs to be opened without damage.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Locksmith', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Window Cleaning Service',
                'description' => 'Monthly window cleaning for a two-story house. Includes both interior and exterior windows.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Cleaning', 'Home Services'],
            ],
            [
                'title' => 'Professional Event Planning',
                'description' => 'Need an event planner for a corporate conference. Approximately 100 attendees, full day event.',
                'priority' => 'high',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Event Planning', 'Business Services'],
            ],
            [
                'title' => 'Home Theater Installation',
                'description' => 'Professional installation of a complete home theater system including projector, screen, and surround sound.',
                'priority' => 'medium',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Electronics', 'Home Services'],
            ],
            [
                'title' => 'Regular Pet Grooming Service',
                'description' => 'Monthly grooming for a medium-sized dog. Includes bath, haircut, and nail trimming.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Pet Care', 'Grooming'],
            ],
            [
                'title' => 'Professional Resume Writing',
                'description' => 'Need help creating a professional resume for a career change in the tech industry.',
                'priority' => 'medium',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Career Services', 'Writing'],
            ],
            [
                'title' => 'Emergency Appliance Repair',
                'description' => 'Refrigerator stopped working. Need immediate repair to prevent food spoilage.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Appliance Repair', 'Emergency Services'],
            ],
            [
                'title' => 'Regular House Painting Service',
                'description' => 'Looking for professional painters to maintain exterior of house. Annual touch-up and repainting as needed.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Painting', 'Home Services'],
            ],
            [
                'title' => 'Professional Video Editing',
                'description' => 'Need help editing wedding video footage. Approximately 8 hours of raw footage to be edited into a 1-hour highlight reel.',
                'priority' => 'medium',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Video Production', 'Media Services'],
            ],
            [
                'title' => 'Emergency Tree Removal',
                'description' => 'Large tree branch fell on roof during storm. Need immediate removal to prevent further damage.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Tree Service', 'Emergency Services'],
            ],
            [
                'title' => 'Regular House Sitting Service',
                'description' => 'Looking for reliable house sitter for regular vacations. Includes plant care and basic maintenance.',
                'priority' => 'low',
                'visibility' => 'private',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['House Sitting', 'Home Services'],
            ],
            [
                'title' => 'Professional Interior Design',
                'description' => 'Need help redesigning living room and dining area. Modern minimalist style preferred.',
                'priority' => 'medium',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Interior Design', 'Home Services'],
            ],
            [
                'title' => 'Emergency Water Damage Restoration',
                'description' => 'Basement flooded after heavy rain. Need immediate water extraction and drying services.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Restoration', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Computer Maintenance',
                'description' => 'Monthly computer maintenance and optimization for small business office. 10 computers total.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['IT Services', 'Business Services'],
            ],
            [
                'title' => 'Professional Voice Over Recording',
                'description' => 'Need voice over artist for a 5-minute corporate video. Professional, clear voice required.',
                'priority' => 'medium',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Voice Over', 'Media Services'],
            ],
            [
                'title' => 'Emergency Garage Door Repair',
                'description' => 'Garage door opener stopped working. Need immediate repair to secure property.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Garage Door', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Pool Cleaning Service',
                'description' => 'Weekly pool cleaning and maintenance for residential pool. Includes chemical balance and equipment check.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Pool Service', 'Home Services'],
            ],
            [
                'title' => 'Professional Social Media Management',
                'description' => 'Need help managing social media accounts for small business. Daily posts and engagement required.',
                'priority' => 'medium',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Social Media', 'Business Services'],
            ],
            [
                'title' => 'Emergency Pest Control',
                'description' => 'Termite infestation discovered in basement. Need immediate treatment to prevent structural damage.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Pest Control', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Car Wash Service',
                'description' => 'Weekly car wash and detailing for company fleet. 5 vehicles total.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Car Wash', 'Automotive'],
            ],
            [
                'title' => 'Professional Translation Services',
                'description' => 'Need translation of business documents from English to Spanish. Approximately 50 pages.',
                'priority' => 'medium',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Translation', 'Business Services'],
            ],
            [
                'title' => 'Emergency Sewer Line Repair',
                'description' => 'Sewer line backup causing flooding in basement. Need immediate inspection and repair.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Plumbing', 'Emergency Services'],
            ],
            [
                'title' => 'Regular HVAC Filter Replacement',
                'description' => 'Monthly replacement of HVAC filters for office building. 20 units total.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['HVAC', 'Business Services'],
            ],
            [
                'title' => 'Professional Bookkeeping Services',
                'description' => 'Monthly bookkeeping and financial reporting for small business.',
                'priority' => 'medium',
                'visibility' => 'private',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Accounting', 'Business Services'],
            ],
            [
                'title' => 'Emergency Glass Repair',
                'description' => 'Broken window in storefront. Need immediate replacement to secure business.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Glass Repair', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Office Cleaning Service',
                'description' => 'Daily cleaning service for small office. 2000 sq ft space.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Cleaning', 'Business Services'],
            ],
            [
                'title' => 'Professional Graphic Design',
                'description' => 'Need logo design and branding materials for new business launch.',
                'priority' => 'medium',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Graphic Design', 'Business Services'],
            ],
            [
                'title' => 'Emergency Fire Damage Cleanup',
                'description' => 'Small kitchen fire caused smoke damage. Need immediate cleanup and restoration.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Restoration', 'Emergency Services'],
            ],
            [
                'title' => 'Regular IT Support Service',
                'description' => 'Weekly IT support and maintenance for small business network.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['IT Services', 'Business Services'],
            ],
            [
                'title' => 'Professional Legal Consultation',
                'description' => 'Need legal advice for small business contract review.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Legal Services', 'Business Services'],
            ],
            [
                'title' => 'Emergency Snow Removal',
                'description' => 'Heavy snowfall blocking driveway and walkways. Need immediate snow removal service.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Snow Removal', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Waste Management Service',
                'description' => 'Weekly garbage and recycling collection for office building.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Waste Management', 'Business Services'],
            ],
            [
                'title' => 'Professional Market Research',
                'description' => 'Need market research and analysis for new product launch.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Market Research', 'Business Services'],
            ],
            [
                'title' => 'Emergency Generator Repair',
                'description' => 'Backup generator failed during power outage. Need immediate repair.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Generator Service', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Security Guard Service',
                'description' => 'Nightly security guard service for office building.',
                'priority' => 'low',
                'visibility' => 'private',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Security', 'Business Services'],
            ],
            [
                'title' => 'Professional Tax Preparation',
                'description' => 'Need help with annual business tax preparation and filing.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Tax Services', 'Business Services'],
            ],
            [
                'title' => 'Emergency Elevator Repair',
                'description' => 'Elevator stuck between floors in office building. Need immediate repair.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Elevator Service', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Janitorial Service',
                'description' => 'Daily janitorial service for commercial building. 10,000 sq ft space.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Janitorial', 'Business Services'],
            ],
            [
                'title' => 'Professional HR Consulting',
                'description' => 'Need HR consulting services for employee handbook development.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['HR Services', 'Business Services'],
            ],
            [
                'title' => 'Emergency Sprinkler System Repair',
                'description' => 'Fire sprinkler system malfunctioning. Need immediate inspection and repair.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Fire Protection', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Landscaping Service',
                'description' => 'Weekly landscaping maintenance for office complex. 2-acre property.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Landscaping', 'Business Services'],
            ],
            [
                'title' => 'Professional Business Coaching',
                'description' => 'Need business coaching services for executive team development.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'recurring',
                'payment_method' => 'credit_card',
                'categories' => ['Business Coaching', 'Business Services'],
            ],
            [
                'title' => 'Emergency Fire Alarm Repair',
                'description' => 'Fire alarm system malfunctioning. Need immediate inspection and repair.',
                'priority' => 'urgent',
                'visibility' => 'public',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Fire Protection', 'Emergency Services'],
            ],
            [
                'title' => 'Regular Parking Lot Maintenance',
                'description' => 'Monthly maintenance of office parking lot. Includes cleaning and line repainting.',
                'priority' => 'low',
                'visibility' => 'public',
                'service_type' => 'recurring',
                'payment_method' => 'bank_transfer',
                'categories' => ['Parking Services', 'Business Services'],
            ],
            [
                'title' => 'Professional Business Plan Development',
                'description' => 'Need help developing comprehensive business plan for startup.',
                'priority' => 'high',
                'visibility' => 'private',
                'service_type' => 'one_time',
                'payment_method' => 'credit_card',
                'categories' => ['Business Planning', 'Business Services'],
            ],
        ];

        ## 5. Finalmente, actualicemos el ServiceRequestSeeder.php para usar las categorías correctamente:
        $categoryMap = [];
        foreach ($categories as $category) {
            $categoryMap[$category->name] = $category;
        }

        foreach ($serviceRequests as $requestData) {
            $user = $users->random();
            $categoryNames = $requestData['categories'];
            unset($requestData['categories']);

            $serviceRequest = ServiceRequest::create([
                'user_id' => $user->id,
                'title' => $requestData['title'],
                'slug' => Str::slug($requestData['title']),
                'description' => $requestData['description'],
                'address' => '123 Main St, Anytown, ST 12345',
                'zip_code' => '12345',
                'latitude' => rand(-90, 90),
                'longitude' => rand(-180, 180),
                'budget' => rand(50, 1000),
                'priority' => $requestData['priority'],
                'visibility' => $requestData['visibility'],
                'service_type' => $requestData['service_type'],
                'payment_method' => $requestData['payment_method'],
                'due_date' => now()->addDays(rand(1, 30)),
                'status' => 'published',
            ]);

            // Attach categories
            $requestCategoryIds = [];
            foreach ($categoryNames as $categoryName) {
                if (isset($categoryMap[$categoryName])) {
                    $requestCategoryIds[] = $categoryMap[$categoryName]->id;
                }
            }

            if (!empty($requestCategoryIds)) {
                $serviceRequest->categories()->attach($requestCategoryIds);
            }
        }
    }
}

