name: Deploy to Amazon Lightsail

on:
  push:
    branches:
      - master   # cámbialo a main si esa es tu rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Amazon Lightsail and deploy API
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.OIDIVI_API_LIGHTSAIL_HOST }}
          username: ${{ secrets.OIDIVI_API_LIGHTSAIL_USER }}
          key: ${{ secrets.OIDIVI_API_LIGHTSAIL_SSH_KEY }}
          script: |
            cd /var/www/oidivi-helper-api

            # Configurar el directorio seguro para Git
            git config --global --add safe.directory /var/www/oidivi-helper-api

            # Resetear y traer últimos cambios
            git reset --hard
            git pull origin master

            # Instalar dependencias de Laravel
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # Aplicar migraciones en producción
            php artisan migrate --force

            # Limpiar y regenerar cachés
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Recargar PHP-FPM (no es necesario reiniciar Nginx siempre)
            sudo systemctl reload php8.2-fpm
